#
# Makefile for the vibrator driver ICs with vibrator driver
#

obj-$(CONFIG_MOTOR_DRV_MAX8997)		+= max8997_vibrator.o
obj-$(CONFIG_MOTOR_DRV_MAX77693)	+= max77693_haptic.o
obj-$(CONFIG_MOTOR_DRV_ISA1200)		+= isa1200_vibrator.o
obj-$(CONFIG_ISA1000_VIBRATOR)	+=ss_brcm_isa1000_haptic.o
obj-$(CONFIG_DRV2603_VIBRATOR)	+=ss_brcm_drv2603_haptic.o
obj-$(CONFIG_BCM_CLS_D_VIBRATOR)	+=ss_brcm_cls_d_haptic.o
obj-$(CONFIG_BCM_SS_VIBRA) += bcm_ss_vibra.o
obj-$(CONFIG_VIBETONZ) 			+= vibrator.o
#obj-y 			+= vibrator.o
vibrator-objs 				+= tspdrv.o
