obj-$(CONFIG_MAP_SDMA) += chal_dmux.o chal_dma.o
obj-$(CONFIG_IPC) += chal_ipc.o chal_icd.o
obj-$(CONFIG_MAP_NAND_CHAL) += chal_nand.o chal_nand_dma_linux.o
obj-$(CONFIG_RTC_DRV_ISLAND) += chal_rtc.o
obj-$(CONFIG_KEYBOARD_KONA) += chal_keypad.o




