EXTRA_CFLAGS  += -Wall -Wstrict-prototypes -Werror

EXTRA_CFLAGS  += -I"include/linux/broadcom"
EXTRA_CFLAGS  += -I"drivers/misc/vc04_services"
EXTRA_CFLAGS  += -I"drivers/misc/vc04_services/interface/vchi"
EXTRA_CFLAGS  += -I"drivers/misc/vc04_services/interface/vchiq_arm"


obj-$(CONFIG_BCM_VC_DISPLAY)  += vc_display.o
