EXTRA_CFLAGS := -Werror
EXTRA_CFLAGS += -DUNDER_LINUX -D_CAPRI_
EXTRA_CFLAGS += -I$(srctree)/drivers/char/broadcom/modem/public/
EXTRA_CFLAGS += -I$(srctree)/include/linux/broadcom/
obj-y += sysparm.o
