/****************************************************************************
*
* Copyright 2010 --2011 Broadcom Corporation.
*
* Unless you and Broadcom execute a separate written software license
* agreement governing use of this software, this software is licensed to you
* under the terms of the GNU General Public License version 2, available at
* http://www.broadcom.com/licenses/GPLv2.php (the "GPL").
*
*****************************************************************************/

#ifndef __CAPRI_PWR_MNGR_H__
#define __CAPRI_PWR_MNGR_H__

#include <mach/rdb/brcm_rdb_pwrmgr.h>

#ifdef CONFIG_DEBUG_FS
#include <linux/stringify.h>
#include <mach/rdb/brcm_rdb_bmdm_pwrmgr.h>
#include <mach/rdb/brcm_rdb_root_clk_mgr_reg.h>
#endif

#define PWRMGR_EVENT_NEGEDGE_CONDITION_ENABLE_MASK	PWRMGR_LCDTE_EVENT_LCDTE_NEGEDGE_CONDITION_ENABLE_MASK
#define PWRMGR_EVENT_POSEDGE_CONDITION_ENABLE_MASK	PWRMGR_LCDTE_EVENT_LCDTE_POSEDGE_CONDITION_ENABLE_MASK
#define PWRMGR_EVENT_CONDITION_ACTIVE_MASK		PWRMGR_LCDTE_EVENT_LCDTE_CONDITION_ACTIVE_MASK

#ifdef CONFIG_DEBUG_FS
extern const char *_capri__event2str[];
#define PWRMGR_EVENT_ID_TO_STR(e) _capri__event2str[e]

#endif

enum {
	LCDTE_EVENT = 0,
	SSP3_FS_EVENT,
	SSP3_RXD_EVENT,
	SSP3_CLK_EVENT,
	SSP2_FS_EVENT,
	SSP2_RXD_EVENT,
	SSP2_CLK_EVENT,
	SSP4_FS_EVENT,
	SSP4_RXD_EVENT,
	SSP4_CLK_EVENT,
	SSP0_FS_EVENT,
	SSP0_RXD_EVENT,
	SSP0_CLK_EVENT,
	DIGCLKREQ_EVENT,
	ANA_SYS_REQ_EVENT,
	HSIC2_UTMI_LINE_STATE0_EVENT,
	UBRX_EVENT,		//0X10
	UBCTSN_EVENT,
	UB2RX_EVENT,
	UB2CTSN_EVENT,
	UB3RX_EVENT,
	UB3CTSN_EVENT,
	UB4RX_EVENT,
	UB4CTSN_EVENT,
	SIMDET_EVENT,
	SIM2DET_EVENT,
	GPIO_91_EVENT,
	GPIO_175_EVENT,
	SDIO4_DATA_3_EVENT,
	SDIO4_DATA_1_EVENT,
	SDDAT3_EVENT,
	SDDAT1_EVENT,
	SSP2_RXD_1_EVENT,	//0X20
	HUB2MM_WAKEUP_EVENT,
	SWCLKTCK_EVENT,
	SWDIOTMS_EVENT,
	KEY_CI_0_EVENT,
	KEY_CI_1_EVENT,
	KEY_CI_2_EVENT,
	KEY_CI_3_EVENT,
	KEY_CI_4_EVENT,
	KEY_CI_5_EVENT,
	KEY_CI_6_EVENT,
	KEY_CI_7_EVENT,
	CAWAKE_EVENT,
	CAREADY_EVENT,
	CAFLAG_EVENT,
	BATRM_EVENT,
	USBDP_EVENT,		//0X30
	USBDN_EVENT,
	USBH2_PHY_RESUME_EVENT,
	PMU_INT_A_EVENT,
	GPIO_8_A_EVENT,
	GPIO_9_A_EVENT,
	GPIO_10_A_EVENT,
	GPIO_11_A_EVENT,
	GPIO_12_A_EVENT,
	GPIO_13_A_EVENT,
	GPIO_54_A_EVENT,
	GPIO_64_A_EVENT,
	GPIO_97_A_EVENT,
	GPIO_102_A_EVENT,
	GPIO_114_A_EVENT,
	GPIO_56_A_EVENT,
	GPIO_140_A_EVENT,	//0X40
	GPIO96_A_EVENT,
	GPIO_142_A_EVENT,
	GPIO_1_A_EVENT,
	GPIO_2_A_EVENT,
	GPIO_92_A_EVENT,
	GPIO_3_A_EVENT,
	GPIO_4_A_EVENT,
	GPIO_5_A_EVENT,
	GPIO_6_A_EVENT,
	GPIO_7_A_EVENT,
	SSP5_CLK_A_EVENT,
	SSP5_RXD_A_EVENT,
	PHY_RESUME_O_AON_1_A_EVENT,
	MODEMBUS_ACTIVE_A_EVENT,
	SSP5_FS_A_EVENT,
	SSP6_CLK_A_EVENT,	//0X50
	SSP6_RXD_A_EVENT,
	ARM_POWER_ON_KONA_FABRIC_A_EVENT,
	SSP6_FS_A_EVENT,
	USBH2_PHY_RESUME_A_EVENT,
	PMU_INT_B_EVENT,
	GPIO_8_B_EVENT,
	GPIO_9_B_EVENT,
	GPIO_10_B_EVENT,
	GPIO_11_B_EVENT,
	GPIO_12_B_EVENT,
	GPIO_13_B_EVENT,
	GPIO_54_B_EVENT,
	GPIO_64_B_EVENT,
	GPIO_97_B_EVENT,
	GPIO_102_B_EVENT,
	GPIO_114_B_EVENT,	//0X60
	GPIO_56_B_EVENT,
	GPIO_140_B_EVENT,
	GPIO96_B_EVENT,
	GPIO_142_B_EVENT,
	GPIO_1_A_B_EVENT,
	GPIO_2_A_B_EVENT,
	GPIO_92_B_EVENT,
	GPIO_3_B_EVENT,
	GPIO_4_B_EVENT,
	GPIO_5_B_EVENT,
	GPIO_6_B_EVENT,
	GPIO_7_B_EVENT,
	SSP5_CLK_B_EVENT,
	SSP5_RXD_B_EVENT,
	PHY_RESUME_O_AON_1_B_EVENT,
	MODEMBUS_ACTIVE_B_EVENT,	//0X70
	SSP5_FS_B_EVENT,
	SSP6_CLK_B_EVENT,
	SSP6_RXD_B_EVENT,
	ARM_POWER_ON_KONA_FABRIC_B_EVENT,
	SSP6_FS_B_EVENT,
	USBH2_PHY_RESUME_B_EVENT,
	COMMON_TIMER_0_EVENT,
	COMMON_TIMER_1_EVENT,
	COMMON_TIMER_2_EVENT,
	COMMON_TIMER_3_EVENT,
	COMMON_TIMER_4_EVENT,
	HSIC2_UTMI_LINE_STATE1_EVENT,
	COMMON_INT_TO_AC_EVENT,
	COMMON_INT_TO_MM_EVENT,
	TZCFG_INT_TO_AC_EVENT,
	DMA_REQUEST_EVENT,	//0X80
	MODEM1_EVENT,
	MODEM2_EVENT,
	MODEM_UART_EVENT,
	BRIDGE_TO_AC_EVENT,
	BRIDGE_TO_MODEM_EVENT,
	VREQ_NONZERO_PI_MODEM_EVENT,
	USBOTG_EVENT,
	GPIO_0_EVENT,
	GPIO_14_EVENT,
	ACI_EVENT,
	SOFTWARE_0_EVENT,
	SOFTWARE_1_EVENT,
	SOFTWARE_2_EVENT,
	VPM_WAKEUP_EVENT,
	ESW_WAKEUP_EVENT,
	GPIO_115_EVENT,		//0X90
	USB0PFT_EVENT,
	USB1PFT_CDN_EVENT,
	ULPI1_EVENT,
	ULPI2_EVENT,		//0X94    

	PWR_MGR_NUM_EVENTS,
};

int capri_pwr_mgr_init(void);
#endif /*__CAPRI_PWR_MNGR_H__*/
